name: inobus_chatwoot_sdk
description: A flutter client sdk for chatwoot. Integrate Chatwoot flutter client into your flutter app and talk to your visitors/users in real time.
version: 1.0.0
homepage: https://github.com/inobus-co/inobus_chatwoot_sdk

environment:
  sdk: "^3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State
  riverpod: ^3.0.0

  # API
  dio: ^5.9.0

  # WS
  web_socket_channel: ^3.0.3

  # Widget
  webview_flutter: ^4.14.1

  # Model
  json_annotation: ^4.11.0

  # Storage
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  flutter_secure_storage: ^10.0.0

  # Util
  path_provider: ^2.0.13
  stream_channel: ^2.1.0
  async: ^2.5.0
  synchronized: ^3.0.0
  equatable: ^2.0.3
  url_launcher: ^6.1.10
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Runner
  build_runner: ^2.12.2

  # Model
  json_serializable: ^6.13.0

  # Storage
  hive_ce_generator: ^1.10.0

  # Lint
  flutter_lints: ^6.0.0

  # Test
  mockito: ^5.3.2

flutter: